#!/usr/bin/env bash
# /usr/local/sbin/kissarch-fixate-1
# fixate 1 subarchive of Poor Man's DMS
# usually called from kissarch-fixate-all
set -x
set -u
set -e

if [ ! -d "$1" ] ; then
   echo "$1 is not a directory."
   echo "example use:"
   echo "kissarch-fixate-1 subarchivedirectory"
   exit 1
fi

KISSARCH_SUBARCHIVE="$1"
if [ ${#KISSARCH_SUBARCHIVE} -lt 30 ] ; then
    echo "$KISSARCH_SUBARCHIVE has length ${#KISSARCH_SUBARCHIVE} which is too short a directory name."
   echo "refusing to operate to avoid big trouble like chmod 0440 /bin/login ."
   exit 1
fi

echo "kissarch-fixate-1 is now about to process directory $KISSARCH_SUBARCHIVE"
# set all files to chmod 0440 (read-only, potentially needing to remove the immutable attribute)
/usr/bin/find "$KISSARCH_SUBARCHIVE" -type f -not -perm 0440 -exec /usr/bin/chattr -i {} \; -exec /usr/bin/chmod -c 0440 {} \;
# set all files to immutable
/usr/bin/find "$KISSARCH_SUBARCHIVE" -type f -exec /usr/local/sbin/kissarch-immutable-1-file {} \;
set -x # kissarch-immutable-1-file does clear the x setting to avoid spamming the log with many filenames that don't need treatment
