# /etc/kissarch/digest.conf
# Shell fragment, to be sourced by various scripts
# Task: set some variables to make generic programs use the right options for creating a list of digests
#  KISSARCH_DIGEST_ALGORITHM = string with digest algorithm, to be used as an option to openssl dgst , without the leading dash. Examples: "sha-256", "sha3-512"
#  KISSARCH_ARCHIVELIST : Array of strings, one element for each archive: path relative to KISSRACH_ARCHIVEBASE , no trailing slash
# test with: bash -x paths.conf
# digest algorithm, 
KISSARCH_DIGEST_ALGORITHM="sha2-256"
KISSARCH_META_DIRECTORY="0-meta" # in-archive directory where digests are going to be stored. Relative to archive root. NO TRAILING SLASH. Will be created if not existing.
KISSARCH_DIGEST_FILENAME_PREFIX="digest-" # beginning of the digest filename. The timestamp comes after this.
KISSARCH_DIGEST_FILENAME_SUFFIX=".$KISSARCH_DIGEST_ALGORITHM" # end of the digest filename. The timestamp comes before this.
KISSARCH_TMP_DIRECTORY=~/.kissarchtmp # NO QUOTES permitted to enable tilde expansion. Temporary files get stored here. No Tilde. NO TRAILING SLASH.
KISSARCH_DIGESTLIST_PREFIX="archive-digest-list-"
