# /etc/kissarch/paths.conf
# Shell fragment, to be sourced by various scripts
# Task: set some variables to make generic programs use local data:
#  KISSARCH_ARCHIVEBASE : string with base directory name, with trailing slash
#  KISSARCH_ARCHIVELIST : Array of strings, one element for each archive: path relative to KISSRACH_ARCHIVEBASE , no trailing slash
# test with: bash -x paths.conf

# base directory, *with* trailing slash, so "/" becomes an option
KISSARCH_ARCHIVEBASE=/home/groups/fibuarchiv/

# delete Array of subarchives, to avoid double entries from previous runs
unset KISSARCH_ARCHIVELIST
declare -a KISSARCH_ARCHIVELIST
for company in 'stut-it' 'Marions Büroservice' ; do
	for year in 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 ; do
		#echo "company=" $company
		#echo "year=" $year
		candidate="${company}/${year}"
		fullcandidate="${KISSARCH_ARCHIVEBASE}${candidate}"
		KISSARCH_ARCHIVELIST+=("$candidate")
	done
done
